export default {
  1: [
    {
      product_id: "7",
      name: "1MB USB Stick",
      price: 5.99,
      stock: 12,
      photo: "photos/Essentials/one-mb-usb.jpg",
      description:
        "This USB stick will hold just about anything as long as it's small in size.",
      rating: 3.9,
    },
    {
      product_id: "8",
      name: "Birdie",
      price: 9.99,
      stock: 18,
      photo: "photos/Essentials/badminton-birder.jpg",
      description: "A spare birdie for badminton.",
      rating: 4.1,
    },
    {
      product_id: "9",
      name: "Bag of Air",
      price: 40.99,
      stock: 200,
      photo: "photos/Essentials/bag-of-air.jpg",
      description: "Who doesn't need air?",
      rating: 3.9,
    },
    {
      product_id: "10",
      name: "Cardboard Box",
      price: 79.99,
      stock: 69,
      photo: "photos/Essentials/cardboard-small.jpg",
      description: "Great for those with the most creative imaginations.",
      rating: 4.9,
    },
    {
      product_id: "11",
      name: "Single Chopstick",
      price: 49.99,
      stock: 99,
      photo: "photos/Essentials/single-chopstick.jpg",
      description: "For those who want to challenge themselves while eating.",
      rating: 4.0,
    },
    {
      product_id: "12",
      name: "Styrofoam Cup",
      price: 12.99,
      stock: 50,
      photo: "photos/Essentials/styrofoam-cup.jpg",
      description: "Great for drinking or magic tricks.",
      rating: 4.3,
    },
  ],
  2: [
    {
      product_id: "29",
      name: "Basket",
      price: 29.99,
      stock: 99,
      photo: "photos/Essentials/basket.jpg",
      description: "A basket for carrying around several small items.",
      rating: 4.6,
    },
    {
      product_id: "30",
      name: "Beach Slippers",
      price: 25.99,
      stock: 80,
      photo: "photos/Essentials/beach-slippers.jpg",
      description:
        "These stylish slippers will go great with any beach/poolside outfit.",
      rating: 4.4,
    },
    {
      product_id: "31",
      name: "Puppy/Small Dog Washing Bucket",
      price: 29.99,
      stock: 50,
      photo: "photos/Essentials/bucket.jpg",
      description: "Puppy not included :(.",
      rating: 4.5,
    },
    {
      product_id: "35",
      name: "Ice Cubes",
      price: 13.99,
      stock: 150,
      photo: "photos/Clearance/ice-cubes.jpg",
      description: "May be water upon arrival.",
      rating: 3.5,
    },
    {
      product_id: "38",
      name: "One Sticky Note",
      price: 6.99,
      stock: 38,
      photo: "photos/Clearance/sticky-note.jpg",
      description: "The smaller you write, the more times you can use it.",
      rating: 4.2,
    },
  ],
};
