export default [
  {
    product_id: "7",
    name: "1MB USB Stick",
    price: 5.99,
    stock: 12,
    photo: "photos/Essentials/one-mb-usb.jpg",
    description:
      "This USB stick will hold just about anything as long as it's small in size.",
    rating: 3.9,
  },
  {
    product_id: "8",
    name: "Birdie",
    price: 9.99,
    stock: 18,
    photo: "photos/Essentials/badminton-birder.jpg",
    description: "A spare birdie for badminton.",
    rating: 4.1,
  },
  {
    product_id: "9",
    name: "Bag of Air",
    price: 40.99,
    stock: 200,
    photo: "photos/Essentials/bag-of-air.jpg",
    description: "Who doesn't need air?",
    rating: 3.9,
  },
  {
    product_id: "10",
    name: "Cardboard Box",
    price: 79.99,
    stock: 69,
    photo: "photos/Essentials/cardboard-small.jpg",
    description: "Great for those with the most creative imaginations.",
    rating: 4.9,
  },
  {
    product_id: "11",
    name: "Single Chopstick",
    price: 49.99,
    stock: 99,
    photo: "photos/Essentials/single-chopstick.jpg",
    description: "For those who want to challenge themselves while eating.",
    rating: 4.0,
  },
  {
    product_id: "12",
    name: "Styrofoam Cup",
    price: 12.99,
    stock: 50,
    photo: "photos/Essentials/styrofoam-cup.jpg",
    description: "Great for drinking or magic tricks.",
    rating: 4.3,
  },
];
