export default [
  {
    product_id: "29",
    name: "Basket",
    price: 29.99,
    stock: 99,
    photo: "photos/Essentials/basket.jpg",
    description: "A basket for carrying around several small items.",
    rating: 4.6,
  },
  {
    product_id: "30",
    name: "Beach Slippers",
    price: 25.99,
    stock: 80,
    photo: "photos/Essentials/beach-slippers.jpg",
    description:
      "These stylish slippers will go great with any beach/poolside outfit.",
    rating: 4.4,
  },
  {
    product_id: "31",
    name: "Puppy/Small Dog Washing Bucket",
    price: 29.99,
    stock: 50,
    photo: "photos/Essentials/bucket.jpg",
    description: "Puppy not included :(.",
    rating: 4.5,
  },
  {
    product_id: "35",
    name: "Ice Cubes",
    price: 13.99,
    stock: 150,
    photo: "photos/Clearance/ice-cubes.jpg",
    description: "May be water upon arrival.",
    rating: 3.5,
  },
  {
    product_id: "38",
    name: "One Sticky Note",
    price: 6.99,
    stock: 38,
    photo: "photos/Clearance/sticky-note.jpg",
    description: "The smaller you write, the more times you can use it.",
    rating: 4.2,
  },
];
