export default [
  {
    product_id: "32",
    name: "Disposable Mask",
    price: 99.99,
    stock: 1,
    photo: "photos/Used/disposable-mask.jpg",
    description: "You have absolutely no reason to purchase this.",
    rating: 4.5,
  },
  {
    product_id: "33",
    name: "Broken Down Truck",
    price: 30.99,
    stock: 2,
    photo: "photos/Used/broken-down-truck.jpg",
    description: "It doesn't work it's just spare parts.",
    rating: 3.3,
  },
  {
    product_id: "34",
    name: "Rusted Cabinet",
    price: 27.99,
    stock: 20,
    photo: "photos/Used/rusted-cabinet.jpg",
    description: "Loud to use but still works.",
    rating: 3.8,
  },
  {
    product_id: "36",
    name: "Shedded Dog Hair",
    price: 8.99,
    stock: 50,
    photo: "photos/Clearance/shredded-dog-hair.jpg",
    description: "We sell anything.",
    rating: 4.2,
  },
];
