const used = {
  1: [
    {
      product_id: "13",
      name: "Bent Spoon",
      price: 39.99,
      stock: 80,
      photo: "photos/Used/bent-spoon.jpg",
      description: "This spoon was bent by Bender Bending Rodriguez himself.",
      rating: 4.5,
    },
    {
      product_id: "14",
      name: "Almost Dead Light Bulb",
      price: 10.99,
      stock: 12,
      photo: "photos/Used/dead-light-bulb.jpg",
      description:
        "A light bulb that can no longer be used for light very soon.",
      rating: 4.5,
    },
    {
      product_id: "15",
      name: "Deflated Soccer Ball",
      price: 12.99,
      stock: 30,
      photo: "photos/Used/deflated-soccer.jpeg",
      description: "Ball pump sold separately and on another website.",
      rating: 4.1,
    },
    {
      product_id: "16",
      name: "Slighty Worn Gardening Gloves",
      price: 24.99,
      stock: 88,
      photo: "photos/Used/gardening-gloves.jpg",
      description: "The gardener who used these said they work great.",
      rating: 4.5,
    },
    {
      product_id: "17",
      name: "Empty Water Bottle",
      price: 8.99,
      stock: 99,
      photo: "photos/Used/water-bottle.jpg",
      description: "Great for holding all types of liquids.",
      rating: 4.2,
    },
    {
      product_id: "18",
      name: "Worn Boots",
      price: 67.99,
      stock: 90,
      photo: "photos/Used/worn-boots.jpg",
      description: "Great for upscale dinner parties or fishing.",
      rating: 4.8,
    },
  ],
  2: [
    {
      product_id: "32",
      name: "Disposable Mask",
      price: 99.99,
      stock: 1,
      photo: "photos/Used/disposable-mask.jpg",
      description: "You have absolutely no reason to purchase this.",
      rating: 4.5,
    },
    {
      product_id: "33",
      name: "Broken Down Truck",
      price: 30.99,
      stock: 2,
      photo: "photos/Used/broken-down-truck.jpg",
      description: "It doesn't work it's just spare parts.",
      rating: 3.3,
    },
    {
      product_id: "34",
      name: "Rusted Cabinet",
      price: 27.99,
      stock: 20,
      photo: "photos/Used/rusted-cabinet.jpg",
      description: "Loud to use but still works.",
      rating: 3.8,
    },
    {
      product_id: "36",
      name: "Shedded Dog Hair",
      price: 8.99,
      stock: 50,
      photo: "photos/Clearance/shredded-dog-hair.jpg",
      description: "We sell anything.",
      rating: 4.2,
    },
  ],
};

export default used;
