export default {
  1: [
    {
      product_id: "25",
      name: "Garden Hose Head",
      price: 22.99,
      stock: 70,
      photo: "photos/Outdoor/garden-hose-head.jpg",
      description: "This is the head of a garden hose.",
      rating: 4.1,
    },
    {
      product_id: "3",
      name: "Basketball Hoop Base",
      price: 99.99,
      stock: 50,
      photo: "photos/Premium/hoop-base.jpg",
      description:
        "Perfect for building your own custom basketball hoop setup.",
      rating: 4.3,
    },
    {
      product_id: "21",
      name: "Rooster Weathervane",
      price: 129.99,
      stock: 30,
      photo: "photos/Vintage/rooster-thing.jpg",
      description: "This item is popular in the midwest.",
      rating: 4.9,
    },
    {
      product_id: "33",
      name: "Broken Down Truck",
      price: 30.99,
      stock: 2,
      photo: "photos/Used/broken-down-truck.jpg",
      description: "It doesn't work it's just spare parts.",
      rating: 3.3,
    },
    {
      product_id: "16",
      name: "Slighty Worn Gardening Gloves",
      price: 24.99,
      stock: 88,
      photo: "photos/Used/gardening-gloves.jpg",
      description: "The gardener who used these said they work great.",
      rating: 4.5,
    },
    {
      product_id: "18",
      name: "Worn Boots",
      price: 67.99,
      stock: 90,
      photo: "photos/Used/worn-boots.jpg",
      description: "Great for upscale dinner parties or fishing.",
      rating: 4.8,
    },
  ],
  2: [
    {
      product_id: "15",
      name: "Deflated Soccer Ball",
      price: 12.99,
      stock: 30,
      photo: "photos/Used/deflated-soccer.jpeg",
      description: "Ball pump sold separately and on another website.",
      rating: 4.1,
    },
  ],
};
