export default {
  1: [
    {
      product_id: "19",
      name: "Cassette",
      price: 13.99,
      stock: 50,
      photo: "photos/Vintage/cassette.jpg",
      description:
        "You should probably own some type of audio playing device at this point.",
      rating: 4.5,
    },
    {
      product_id: "20",
      name: "Home Telephone",
      price: 30.99,
      stock: 20,
      photo: "photos/Vintage/phone.jpg",
      description: "Cell phones have been out for decades.",
      rating: 4.0,
    },
    {
      product_id: "21",
      name: "Rooster Weathervane",
      price: 129.99,
      stock: 30,
      photo: "photos/Vintage/rooster-thing.jpg",
      description: "This item is popular in the midwest.",
      rating: 4.9,
    },
    {
      product_id: "22",
      name: "Slinky",
      price: 19.99,
      stock: 80,
      photo: "photos/Vintage/slinky.jpg",
      description: "A seasoned distraction from being productive.",
      rating: 3.6,
    },
    {
      product_id: "23",
      name: "Typewriter",
      price: 73.99,
      stock: 20,
      photo: "photos/Vintage/typewriter.jpg",
      description: "Used mostly as a decoration.",
      rating: 3.8,
    },
    {
      product_id: "24",
      name: "VHS",
      price: 10.99,
      stock: 0,
      photo: "photos/Vintage/vhs.jpg",
      description: "Useful as a frisbee.",
      rating: 3.7,
    },
  ],
};
