export default [
  {
    product_id: "1",
    name: "Bike Handlebars",
    price: 99.99,
    stock: 70,
    photo: "photos/Premium/bike-handlebar.jpg",
    description: "Handlebars to fit on a bike, even an imaginary one.",
    rating: 4.6,
  },
  {
    product_id: "2",
    name: "Fancy Napkin",
    price: 399.99,
    stock: 30,
    photo: "photos/Premium/fancy-napkin.jpg",
    description:
      "This napkin will surely keep your guests in the mood for fine dining.",
    rating: 4.8,
  },
  {
    product_id: "3",
    name: "Basketball Hoop Base",
    price: 99.99,
    stock: 50,
    photo: "photos/Premium/hoop-base.jpg",
    description: "Perfect for building your own custom basketball hoop setup.",
    rating: 4.3,
  },
  {
    product_id: "4",
    name: "Magnet",
    price: 69.99,
    stock: 15,
    photo: "photos/Premium/magnet.jpg",
    description: "It's attractive.",
    rating: 5.0,
  },
  {
    product_id: "5",
    name: "Ribs",
    price: 149.99,
    stock: 1,
    photo: "photos/Premium/ribs.jpg",
    description: "The tastiest ribs you won't find anywhere else.",
    rating: 4.9,
  },
  {
    product_id: "6",
    name: "Single Red Shoelace",
    price: 189.99,
    stock: 12,
    photo: "photos/Premium/single-red-shoelace.jpg",
    description: "Perfect gift to show your affection and appreciation.",
    rating: 4.5,
  },
];
