export default [
  {
    product_id: "35",
    name: "Ice Cubes",
    price: 13.99,
    stock: 150,
    photo: "photos/Clearance/ice-cubes.jpg",
    description: "May be water upon arrival.",
    rating: 3.5,
  },
  {
    product_id: "36",
    name: "Shedded Dog Hair",
    price: 8.99,
    stock: 50,
    photo: "photos/Clearance/shredded-dog-hair.jpg",
    description: "We sell anything.",
    rating: 4.2,
  },
  {
    product_id: "37",
    name: "Stonehenge",
    price: 2.99,
    stock: 0,
    photo: "photos/Clearance/skynews-stonehenge-monument_4583271.jpg",
    description: "A bunch of mysterious rocks.",
    rating: 3.8,
  },
  {
    product_id: "38",
    name: "One Sticky Note",
    price: 6.99,
    stock: 38,
    photo: "photos/Clearance/sticky-note.jpg",
    description: "The smaller you write, the more times you can use it.",
    rating: 4.2,
  },
];
