export default [
  {
    product_id: "1",
    name: "Bike Handlebars",
    price: 99.99,
    stock: 70,
    photo: "",
    description: "Handlebars to fit on a bike, even an imaginary one.",
    rating: 4.6,
  },
  {
    product_id: "2",
    name: "Fancy Napkin",
    price: 399.99,
    stock: 30,
    photo: "",
    description:
      "This napkin will surely keep your guests in the mood for fine dining.",
    rating: 4.8,
  },
  {
    product_id: "3",
    name: "Basketball Hoop Base",
    price: 99.99,
    stock: 50,
    photo: "",
    description: "Perfect for building your own custom basketball hoop setup.",
    rating: 4.3,
  },
  {
    product_id: "4",
    name: "Magnet",
    price: 69.99,
    stock: 15,
    photo: "",
    description: "It's attractive.",
    rating: 5.0,
  },
  {
    product_id: "5",
    name: "Ribs",
    price: 149.99,
    stock: 1,
    photo: "",
    description: "The tastiest ribs you won't find anywhere else.",
    rating: 4.9,
  },
  {
    product_id: "6",
    name: "Single Red Shoelace",
    price: 189.99,
    stock: 12,
    photo: "",
    description: "Perfect gift to show your affection and appreciation.",
    rating: 4.5,
  },
  {
    product_id: "7",
    name: "1MB USB Stick",
    price: 5.99,
    stock: 12,
    photo: "",
    description:
      "This USB stick will hold just about anything as long as it's small in size.",
    rating: 3.9,
  },
  {
    product_id: "8",
    name: "Birdie",
    price: 9.99,
    stock: 18,
    photo: "",
    description: "A spare birdie for badminton.",
    rating: 4.1,
  },
  {
    product_id: "9",
    name: "Bag of Air",
    price: 40.99,
    stock: 200,
    photo: "",
    description: "Who doesn't need air?",
    rating: 3.9,
  },
  {
    product_id: "10",
    name: "Cardboard Box",
    price: 79.99,
    stock: 69,
    photo: "",
    description: "Great for those with the most creative imaginations.",
    rating: 4.9,
  },
  {
    product_id: "11",
    name: "Single Chopstick",
    price: 49.99,
    stock: 99,
    photo: "",
    description: "For those who want to challenge themselves while eating.",
    rating: 4.0,
  },
  {
    product_id: "12",
    name: "Styrofoam Cup",
    price: 12.99,
    stock: 50,
    photo: "",
    description: "Great for drinking or magic tricks.",
    rating: 4.3,
  },
  {
    product_id: "13",
    name: "Bent Spoon",
    price: 39.99,
    stock: 80,
    photo: "",
    description: "This spoon was bent by Bender Bending Rodriguez himself.",
    rating: 4.5,
  },
  {
    product_id: "14",
    name: "Almost Dead Light Bulb",
    price: 10.99,
    stock: 12,
    photo: "",
    description: "A light bulb that can no longer be used for light very soon.",
    rating: 4.5,
  },
  {
    product_id: "15",
    name: "Deflated Soccer Ball",
    price: 12.99,
    stock: 30,
    photo: "",
    description: "Ball pump sold separately and on another website.",
    rating: 4.1,
  },
  {
    product_id: "16",
    name: "Slighty Worn Gardening Gloves",
    price: 24.99,
    stock: 88,
    photo: "",
    description: "The gardener who used these said they work great.",
    rating: 4.5,
  },
  {
    product_id: "17",
    name: "Empty Water Bottle",
    price: 8.99,
    stock: 99,
    photo: "",
    description: "Great for holding all types of liquids.",
    rating: 4.2,
  },
  {
    product_id: "18",
    name: "Worn Boots",
    price: 67.99,
    stock: 90,
    photo: "",
    description: "Great for upscale dinner parties or fishing.",
    rating: 4.8,
  },
  {
    product_id: "19",
    name: "Cassette",
    price: 13.99,
    stock: 50,
    photo: "",
    description:
      "You should probably have some type of audio playing device at this point.",
    rating: 4.5,
  },
  {
    product_id: "20",
    name: "Home Telephone",
    price: 30.99,
    stock: 20,
    photo: "",
    description: "Cell phones have been out for decades.",
    rating: 4.0,
  },
  {
    product_id: "21",
    name: "Rooster Weathervane",
    price: 129.99,
    stock: 30,
    photo: "",
    description: "This item is popular in the midwest.",
    rating: 4.9,
  },
  {
    product_id: "22",
    name: "Slinky",
    price: 19.99,
    stock: 80,
    photo: "",
    description: "A great distraction from being productive.",
    rating: 3.6,
  },
  {
    product_id: "23",
    name: "Typewriter",
    price: 73.99,
    stock: 20,
    photo: "",
    description: "Used mostly as a decoration.",
    rating: 3.8,
  },
  {
    product_id: "24",
    name: "VHS",
    price: 10.99,
    stock: 0,
    photo: "",
    description: "Useful as a frisbee.",
    rating: 3.7,
  },
  {
    product_id: "25",
    name: "Garden Hose Head",
    price: 22.99,
    stock: 70,
    photo: "",
    description: "This is the head of a garden hose.",
    rating: 4.1,
  },
  {
    product_id: "26",
    name: "Large Teddy",
    price: 149.99,
    stock: 5,
    photo: "",
    description:
      "Teddy boi is very large and fluffy. Works great for cuddling.",
    rating: 5.0,
  },
  {
    product_id: "27",
    name: "Raw Fish",
    price: 99.99,
    stock: 40,
    photo: "",
    description: "Just a raw fish.",
    rating: 4.4,
  },
  {
    product_id: "28",
    name: "Tangled Rope",
    price: 59.99,
    stock: 60,
    photo: "",
    description: "If untangled it can provide many uses",
    rating: 4.3,
  },
  {
    product_id: "29",
    name: "Basket",
    price: 29.99,
    stock: 99,
    photo: "",
    description: "A basket for carrying around several small items.",
    rating: 4.6,
  },
  {
    product_id: "30",
    name: "Beach Slippers",
    price: 25.99,
    stock: 80,
    photo: "",
    description:
      "These stylish slippers will go great with any beach/poolside outfit.",
    rating: 4.4,
  },
  {
    product_id: "31",
    name: "Puppy/Small Dog Washing Bucket",
    price: 29.99,
    stock: 50,
    photo: "",
    description: "Puppy not included :(.",
    rating: 4.5,
  },
  {
    product_id: "32",
    name: "Disposable Mask",
    price: 99.99,
    stock: 1,
    photo: "",
    description: "You have absolutely no reason to purchase this.",
    rating: 4.5,
  },
  {
    product_id: "33",
    name: "Broken Down Truck",
    price: 30.99,
    stock: 2,
    photo: "",
    description: "It doesn't work it's just spare parts.",
    rating: 3.3,
  },
  {
    product_id: "34",
    name: "Rusted Cabinet",
    price: 27.99,
    stock: 20,
    photo: "",
    description: "Loud to use but still works.",
    rating: 3.8,
  },
];
