const all = [
  {
    product_id: "0",
    name: "Bike Handlebars",
    price: 99.99,
    stock: 70,
    photo: "photos/Premium/bike-handlebar.jpg",
    description: "Handlebars to fit on a bike, even an imaginary one.",
    rating: 4.6,
  },
  {
    product_id: "1",
    name: "Fancy Napkin",
    price: 399.99,
    stock: 30,
    photo: "photos/Premium/fancy-napkin.jpg",
    description:
      "This napkin will surely keep your guests in the mood for fine dining.",
    rating: 4.8,
  },
  {
    product_id: "2",
    name: "Basketball Hoop Base",
    price: 99.99,
    stock: 50,
    photo: "photos/Premium/hoop-base.jpg",
    description: "Perfect for building your own custom basketball hoop setup.",
    rating: 4.3,
  },
  {
    product_id: "3",
    name: "Magnet",
    price: 69.99,
    stock: 15,
    photo: "photos/Premium/magnet.jpg",
    description: "It's attractive.",
    rating: 5.0,
  },
  {
    product_id: "4",
    name: "Ribs",
    price: 149.99,
    stock: 1,
    photo: "photos/Premium/ribs.jpg",
    description: "The tastiest ribs you won't find anywhere else.",
    rating: 4.9,
  },
  {
    product_id: "5",
    name: "Single Red Shoelace",
    price: 189.99,
    stock: 12,
    photo: "photos/Premium/single-red-shoelace.jpg",
    description: "Perfect gift to show your affection and appreciation.",
    rating: 4.5,
  },
  {
    product_id: "6",
    name: "1MB USB Stick",
    price: 5.99,
    stock: 12,
    photo: "photos/Essentials/one-mb-usb.jpg",
    description:
      "This USB stick will hold just about anything as long as it's small in size.",
    rating: 3.9,
  },
  {
    product_id: "7",
    name: "Birdie",
    price: 9.99,
    stock: 18,
    photo: "photos/Essentials/badminton-birder.jpg",
    description: "A spare birdie for badminton.",
    rating: 4.1,
  },
  {
    product_id: "8",
    name: "Bag of Air",
    price: 40.99,
    stock: 200,
    photo: "photos/Essentials/bag-of-air.jpg",
    description: "Who doesn't need air?",
    rating: 3.9,
  },
  {
    product_id: "9",
    name: "Cardboard Box",
    price: 79.99,
    stock: 69,
    photo: "photos/Essentials/cardboard-small.jpg",
    description: "Great for those with the most creative imaginations.",
    rating: 4.9,
  },
  {
    product_id: "10",
    name: "Single Chopstick",
    price: 49.99,
    stock: 99,
    photo: "photos/Essentials/single-chopstick.jpg",
    description: "For those who want to challenge themselves while eating.",
    rating: 4.0,
  },
  {
    product_id: "11",
    name: "Styrofoam Cup",
    price: 12.99,
    stock: 50,
    photo: "photos/Essentials/styrofoam-cup.jpg",
    description: "Great for drinking or magic tricks.",
    rating: 4.3,
  },
  {
    product_id: "12",
    name: "Bent Spoon",
    price: 39.99,
    stock: 80,
    photo: "photos/Used/bent-spoon.jpg",
    description: "This spoon was bent by Bender Bending Rodriguez himself.",
    rating: 4.5,
  },
  {
    product_id: "13",
    name: "Almost Dead Light Bulb",
    price: 10.99,
    stock: 12,
    photo: "photos/Used/dead-light-bulb.jpg",
    description: "A light bulb that can no longer be used for light very soon.",
    rating: 4.5,
  },
  {
    product_id: "14",
    name: "Deflated Soccer Ball",
    price: 12.99,
    stock: 30,
    photo: "photos/Used/deflated-soccer.jpeg",
    description: "Ball pump sold separately and on another website.",
    rating: 4.1,
  },
  {
    product_id: "15",
    name: "Slighty Worn Gardening Gloves",
    price: 24.99,
    stock: 88,
    photo: "photos/Used/gardening-gloves.jpg",
    description: "Previous owner recommends.",
    rating: 4.5,
  },
  {
    product_id: "16",
    name: "Empty Water Bottle",
    price: 8.99,
    stock: 99,
    photo: "photos/Used/water-bottle.jpg",
    description: "Great for holding all types of liquids.",
    rating: 4.2,
  },
  {
    product_id: "17",
    name: "Worn Boots",
    price: 67.99,
    stock: 90,
    photo: "photos/Used/worn-boots.jpg",
    description: "Great for upscale dinner parties or fishing.",
    rating: 4.8,
  },
  {
    product_id: "18",
    name: "Cassette",
    price: 13.99,
    stock: 50,
    photo: "photos/Vintage/cassette.jpg",
    description:
      "You should probably own some type of audio playing device at this point.",
    rating: 4.5,
  },
  {
    product_id: "19",
    name: "Home Telephone",
    price: 30.99,
    stock: 20,
    photo: "photos/Vintage/phone.jpg",
    description: "Cell phones have been out for decades.",
    rating: 4.0,
  },
  {
    product_id: "20",
    name: "Rooster Weathervane",
    price: 129.99,
    stock: 30,
    photo: "photos/Vintage/rooster-thing.jpg",
    description: "This item is popular in the midwest.",
    rating: 4.9,
  },
  {
    product_id: "21",
    name: "Slinky",
    price: 19.99,
    stock: 80,
    photo: "photos/Vintage/slinky.jpg",
    description: "A seasoned distraction from being productive.",
    rating: 3.6,
  },
  {
    product_id: "22",
    name: "Typewriter",
    price: 73.99,
    stock: 20,
    photo: "photos/Vintage/typewriter.jpg",
    description: "Used mostly as a decoration.",
    rating: 3.8,
  },
  {
    product_id: "23",
    name: "VHS",
    price: 10.99,
    stock: 0,
    photo: "photos/Vintage/vhs.jpg",
    description: "Useful as a frisbee.",
    rating: 3.7,
  },
  {
    product_id: "24",
    name: "Garden Hose Head",
    price: 22.99,
    stock: 70,
    photo: "photos/Outdoor/garden-hose-head.jpg",
    description: "This is the head of a garden hose.",
    rating: 4.1,
  },
  {
    product_id: "25",
    name: "Large Teddy",
    price: 149.99,
    stock: 5,
    photo: "photos/Premium/large-teddy.jpg",
    description:
      "Teddy boi is very large and fluffy. Works great for cuddling.",
    rating: 5.0,
  },
  {
    product_id: "26",
    name: "Raw Fish",
    price: 99.99,
    stock: 40,
    photo: "photos/Premium/raw-fish.jpg",
    description: "Just a raw fish.",
    rating: 4.4,
  },
  {
    product_id: "27",
    name: "Tangled Rope",
    price: 59.99,
    stock: 60,
    photo: "photos/Premium/tangled-rope.jpg",
    description: "If untangled it can provide many uses",
    rating: 4.3,
  },
  {
    product_id: "28",
    name: "Basket",
    price: 29.99,
    stock: 99,
    photo: "photos/Essentials/basket.jpg",
    description: "A basket for carrying around several small items.",
    rating: 4.6,
  },
  {
    product_id: "29",
    name: "Beach Slippers",
    price: 25.99,
    stock: 80,
    photo: "photos/Essentials/beach-slippers.jpg",
    description:
      "These stylish slippers will go great with any beach/poolside outfit.",
    rating: 4.4,
  },
  {
    product_id: "30",
    name: "Small Washing Bucket",
    price: 29.99,
    stock: 50,
    photo: "photos/Essentials/bucket.jpg",
    description: "Puppy not included :(.",
    rating: 4.5,
  },
  {
    product_id: "31",
    name: "Disposable Mask",
    price: 99.99,
    stock: 1,
    photo: "photos/Used/disposable-mask.jpg",
    description: "You have absolutely no reason to purchase this.",
    rating: 4.5,
  },
  {
    product_id: "32",
    name: "Broken Down Truck",
    price: 30.99,
    stock: 2,
    photo: "photos/Used/broken-down-truck.jpg",
    description: "It doesn't work it's just spare parts.",
    rating: 3.3,
  },
  {
    product_id: "33",
    name: "Rusted Cabinet",
    price: 27.99,
    stock: 20,
    photo: "photos/Used/rusted-cabinet.jpg",
    description: "Loud to use but still works.",
    rating: 3.8,
  },
  {
    product_id: "34",
    name: "Ice Cubes",
    price: 13.99,
    stock: 150,
    photo: "photos/Clearance/ice-cubes.jpg",
    description: "May be water upon arrival.",
    rating: 3.5,
  },
  {
    product_id: "35",
    name: "Shedded Dog Hair",
    price: 8.99,
    stock: 50,
    photo: "photos/Clearance/shredded-dog-hair.jpg",
    description: "We sell anything.",
    rating: 4.2,
  },
  {
    product_id: "36",
    name: "Stonehenge",
    price: 2.99,
    stock: 0,
    photo: "photos/Clearance/skynews-stonehenge-monument_4583271.jpg",
    description: "A bunch of mysterious rocks.",
    rating: 3.8,
  },
  {
    product_id: "37",
    name: "One Sticky Note",
    price: 6.99,
    stock: 38,
    photo: "photos/Clearance/sticky-note.jpg",
    description: "The smaller you write, the more times you can use it.",
    rating: 4.2,
  },
];

export default all;
